import joblib, os
from sklearn.feature_extraction.text import TfidfVectorizer

MODELS_DIR = "models"

training_texts = [
    "elderly man collapsed not breathing need ambulance urgently heart stopped",
    "passenger unconscious cardiac arrest unresponsive on floor urgent help",
    "woman having seizure convulsions shaking uncontrollable please call ambulance",
    "man choking on food cannot breathe turning blue emergency help now",
    "passenger bleeding heavily from head injury accident urgent ambulance needed",
    "child collapsed fever very high unconscious not waking up emergency",
    "stroke symptoms face drooping arm weakness speech slurred call 119",
    "diabetic passenger low blood sugar unconscious insulin needed immediately",
    "heart attack chest pain radiating arm left side ambulance dispatch now",
    "elderly woman fell down stairs broken leg bleeding urgent medical help",
    "passenger poisoning vomiting severely difficulty breathing urgent",
    "pregnant woman contractions severe labor emergency hospital now",
    "newborn infant baby stopped breathing urgent ambulance please help",
    "electrocution passenger touched exposed wire unconscious emergency",
    "severe allergic reaction anaphylaxis throat closing cannot breathe epipen",
    "passenger overdose drug unconscious not responding pupils dilated",
    "hemorrhaging severe internal bleeding stomach pain urgent surgery",
    "fracture broken bone visible bone protruding severe pain bleeding",
    "asthma attack passenger no inhaler cannot breathe turning blue",
    "drowning passenger fell into water near bridge unconscious pulled out",
    "man with knife threatening passengers stabbing attack emergency",
    "armed robbery gunman on bus pointing weapon demanding money",
    "shooting happened on bus passenger shot bleeding critical condition",
    "bomb threat suspicious package left on bus explosive device found",
    "hijacking driver forced gunpoint to change route hostage situation",
    "sexual assault rape happening on bus back seat emergency police",
    "stabbing blood everywhere multiple passengers injured police needed",
    "terrorist threat armed men took over bus passengers held hostage",
    "gang fight weapons drawn knives dangerous multiple people injured",
    "murder dead body found on bus passenger not breathing stab wounds",
    "man assaulting passenger punching kicking need police immediately",
    "robbery theft stolen wallet phone bag snatched on bus",
    "drunk aggressive man threatening female passengers shouting intimidating",
    "fight broke out multiple passengers involved police needed urgently",
    "harassment following female passenger inappropriate touching groping",
    "man exposing himself indecent exposure to female passengers disgusting",
    "recording women secretly hidden camera voyeur illegal disgusting",
    "intoxicated passenger extremely drunk vomiting aggressive behaviour",
    "thief pickpocket operating stealing passengers valuables reported",
    "threatening with weapon dangerous man on bus other passengers scared",
    "brake failure bus cannot stop out of control dangerous speed highway",
    "driver reckless dangerous speeding wrong side overtaking accident risk",
    "bus on fire smoke filling cabin passengers evacuating emergency",
    "engine failure bus broken down highway dangerous location emergency",
    "tire burst bus swerving uncontrollable dangerous crash risk",
    "driver drunk alcohol smell reckless dangerous driving urgent",
    "accident collision bus hit car injuries sustained passengers hurt",
    "wrong side driving head on collision risk dangerous urgent police",
    "bus mechanical failure steering not working driver losing control",
    "flood water engine stalled stuck middle road passengers trapped",
    "driver verbally abusing passengers shouting rude behavior unacceptable",
    "conductor overcharging passengers demanding extra fare illegal",
    "driver using phone while driving dangerous distracted unsafe",
    "passenger harassing other commuters repeatedly police intervention needed",
    "driver discriminating refusing passengers based on appearance",
    "argument between driver conductor and passenger getting heated",
    "bus driver ignoring stops not stopping at designated bus stops",
    "overcrowding dangerous number passengers packed safety concern",
    "broken seat passenger fell injured minor cuts bruises",
    "air conditioning not working extreme heat passengers distressed",
    "bus breakdown stopped middle road passengers stranded help needed",
    "engine overheating smoke from hood stopped on road",
    "door stuck passengers cannot exit broken mechanism",
    "transmission failure bus cannot move gear stuck breakdown",
    "flat tire changed side road passengers waiting replacement bus",
    "electrical fault lights not working driving in dark unsafe",
    "windshield cracked visibility poor dangerous for driver",
    "fuel leak smell diesel strong fire risk dangerous",
    "battery dead bus wont start passengers waiting long time",
    "suspension broken bus bouncing dangerously uncomfortable unsafe",
    "driver slightly late traffic jam delay moderate acceptable",
    "minor argument passenger conductor resolved peacefully",
    "small scratch on bus no injuries minor incident logged",
    "passenger left item on bus lost property recovered",
    "driver took slightly longer route minor deviation noted",
    "air freshener broken smell unpleasant minor complaint",
    "seat cushion torn uncomfortable minor repair needed",
    "window stuck open cold wind minor discomfort passenger",
    "music playing loud driver request turn down minor",
    "passenger eating on bus messy minor violation noted",
    "sorry wrong button pressed by accident false alarm please ignore",
    "test alert testing system functionality nothing happened here",
    "pocket dial accidental press nothing wrong everything fine",
    "false alarm sorry nothing to report all passengers safe",
    "mistake pressed emergency button by accident everything okay",
    "nothing happened ignore this testing application ok cancel",
    "accidentally pressed this everything fine no emergency here",
    "wrong button sorry everything is perfectly fine here",
    "nothing wrong just testing bye ignore please cancel this",
    "resolved fine now misunderstanding no emergency cancel this",
    "dummy test alert please disregard all is well normal",
    "training drill test scenario not real emergency disregard",
    "accidentally activated sorry no real problem everything normal",
    "system test automated check no action required please ignore",
    "medical emergency passenger collapsed elderly man heart breathing stopped",
    "criminal activity knife weapon threat dangerous urgent police dispatch",
    "bus breakdown highway engine failure passengers stranded roadside",
    "harassment inappropriate behaviour passenger reporting incident",
    "other emergency urgent situation needs attention immediate response",
    "elderly passenger fell stepped wrong unconscious possible fracture",
    "multiple passengers injured bus accident collision emergency services",
    "driver aggressive road rage dangerous driving complaint urgent",
    "passenger suspicious behaviour watching children inappropriate concern",
    "bus fire small smoke visible engine stopped passengers evacuated",
    "woman alone being followed harassed feel unsafe frightened scared",
    "serious medical condition patient deteriorating needs urgent care now",
    "violent passenger kicked seat threatened punched driver face",
    "gas leak smell inside bus nausea passengers vomiting evacuation",
    "driver exhausted falling asleep wheel dangerous night shift",
    "child unaccompanied minor lost crying no parent guardian present",
    "passenger with disability needs assistance wheelchair stuck doorway",
    "overcrowded extremely dangerous people hanging door risk injury",
    "road accident bus involved injury passenger thrown forward",
    "dispute escalating violence imminent need police intervention now",
    "unconscious passenger not breathing pulse weak critical condition",
    "emergency breakdown highway fast lane dangerous approaching vehicles",
    "weapon drawn passenger threatened shot stabbed bleeding urgent",
    "medical help needed immediately passenger deteriorating fast hospital",
    "police required criminal activity violent dangerous situation bus",
    "ambulance needed urgently passenger condition worsening critical",
    "driver lost control bus swerving passengers screaming danger",
    "fire spreading bus engine burning passengers jumping out emergency",
]

print("Training corpus: {} documents".format(len(training_texts)))

tfidf = TfidfVectorizer(
    max_features=799,
    ngram_range=(1, 2),
    min_df=1,
    sublinear_tf=True,
)
tfidf.fit(training_texts)

actual = len(tfidf.vocabulary_)
print("Vocabulary size: {} features".format(actual))
print("Model expects: 799 TF-IDF + 15 structural = 814 total")

out_path = os.path.join(MODELS_DIR, "tfidf_vectorizer.pkl")
joblib.dump(tfidf, out_path)
print("Saved to: {}".format(out_path))
print("Done! Restart the ML service now.")
