import joblib
import os
from sklearn.feature_extraction.text import TfidfVectorizer

MODELS_DIR = "models"

training_texts = [
    "the driver was very rude and aggressive towards passengers",
    "excellent service very punctual and friendly driver today",
    "bus was dirty and smelled bad very uncomfortable journey",
    "driver was speeding dangerously on the highway very scary",
    "very clean bus arrived on time great experience overall",
    "driver was polite and helpful good journey comfortable seats",
    "overcrowded bus very uncomfortable standing room only terrible",
    "late arrival poor service disappointed with the trip today",
    "smooth ride comfortable seats good air conditioning pleasant",
    "driver ignored stops and was very rude to passengers",
    "amazing experience will definitely use this service again recommended",
    "terrible driver was on phone whole time dangerous driving",
    "good value for money comfortable journey arrived on time",
    "bus broke down in the middle of the road stranded",
    "very professional driver clean vehicle good service overall",
    "driver was drunk and driving recklessly very scary dangerous",
    "pleasant journey friendly staff clean comfortable bus seats",
    "horrible experience driver was shouting at passengers very rude",
    "on time departure smooth ride satisfied with service today",
    "bus was late by 30 minutes very inconvenient frustrating",
    "great driver very polite and helpful throughout the journey",
    "worst bus ride ever dirty seats bad smell horrible",
    "driver took wrong route and we were very late",
    "comfortable journey arrived on time very happy satisfied",
    "rude conductor overcharged passengers very dishonest behavior",
    "excellent punctuality clean bus friendly staff great service",
    "dangerous driving too fast on narrow roads very scary",
    "good service reasonable fare comfortable journey pleasant ride",
    "driver was using phone while driving very unsafe dangerous",
    "nice clean bus good air conditioning arrived on time",
    "driver stopped too long at each station very frustrating",
    "very good experience will use again highly recommended service",
    "bus was overcrowded no space to breathe terrible experience",
    "driver was courteous and professional good trip overall",
    "not bad the driver was acceptable average service today",
    "the driver was not that good stops too long station",
    "it was good the driver was not bad overall acceptable",
    "average experience nothing special about the journey today",
    "driver needs improvement but overall acceptable ride decent",
    "decent service could be better but not terrible overall",
    "the bus was on time and driver was friendly helpful",
    "very bad experience driver was aggressive and rude passengers",
    "good journey comfortable seats arrived destination on time today",
    "driver was careless and irresponsible very dangerous driving",
    "excellent bus service clean comfortable punctual highly recommend",
    "terrible experience overcrowded dirty bus late arrival frustrated",
    "professional driver courteous helpful pleasant comfortable journey",
    "dangerous speeding reckless driving scary unsafe uncomfortable",
    "clean tidy bus punctual friendly driver great service",
    "rude aggressive driver poor service late departure frustrating",
    "comfortable seats air conditioning good driver on time arrival",
    "dirty smelly bus uncomfortable seats terrible experience horrible",
    "excellent punctual service friendly driver clean comfortable bus",
    "driver was very helpful and polite throughout journey great",
    "overcrowded uncomfortable no seats standing dangerous overloaded",
    "smooth comfortable ride on time departure arrival satisfied",
    "driver was aggressive rude shouting passengers terrible experience",
    "clean comfortable bus friendly driver punctual excellent service",
    "very late departure poor service driver was rude today",
    "good journey overall driver was acceptable comfortable seats",
    "terrible driver speeding reckless dangerous scary highway",
    "excellent service clean bus comfortable seats friendly driver",
    "driver was using mobile phone dangerous unsafe irresponsible",
    "pleasant comfortable journey helpful driver arrived on time",
    "horrible dirty bus bad smell terrible uncomfortable experience",
    "good punctual service clean bus professional courteous driver",
    "driver was very rude aggressive shouting horrible experience",
    "comfortable clean bus on time arrival friendly staff",
    "dangerous driving fast speed reckless unsafe passengers scared",
    "nice journey comfortable seats arrived on time satisfied",
    "driver ignored passenger requests rude unhelpful terrible service",
    "excellent clean comfortable bus friendly driver punctual arrival",
    "very bad driver reckless dangerous unsafe horrible experience",
    "good service comfortable journey arrived destination time",
    "driver was helpful polite professional excellent service overall",
    "dirty overcrowded bus uncomfortable seats terrible horrible",
    "smooth ride clean bus on time friendly driver great",
    "driver was aggressive rude passengers uncomfortable horrible",
    "comfortable journey good service driver was polite helpful",
    "very dirty smelly bus terrible experience uncomfortable seats",
    "excellent driver punctual clean bus comfortable seats great",
    "dangerous reckless driving speeding unsafe highway scary",
    "good comfortable journey driver was acceptable on time",
    "driver was very polite helpful professional excellent service",
    "horrible overcrowded dirty bus terrible uncomfortable experience",
    "clean comfortable bus friendly driver on time arrival great",
    "driver was rude aggressive shouting passengers very bad",
    "pleasant journey comfortable seats on time arrival satisfied",
    "terrible service late arrival dirty bus uncomfortable horrible",
    "excellent professional driver clean comfortable bus punctual",
    "very bad experience rude driver dangerous driving unsafe",
    "good journey on time arrival comfortable seats driver helpful",
    "driver was courteous professional helpful pleasant comfortable",
    "dirty smelly overcrowded bus horrible terrible experience",
    "clean bus punctual friendly driver excellent comfortable journey",
    "driver was aggressive rude dangerous speeding scary horrible",
    "comfortable journey good driver clean bus on time arrival",
    "excellent service friendly driver punctual clean comfortable bus",
    "terrible driver rude aggressive shouting passengers bad experience",
    "good comfortable clean bus on time arrival driver helpful",
    "driver was very professional courteous excellent service",
    "horrible dirty overcrowded bus late arrival terrible experience",
    "smooth ride on time departure comfortable seats friendly driver",
    "driver was rude unhelpful poor service terrible experience",
    "clean comfortable bus excellent service friendly professional driver",
    "very bad dangerous reckless driving unsafe scary experience",
    "good journey comfortable seats driver acceptable on time",
    "driver was polite helpful professional pleasant comfortable journey",
    "terrible dirty smelly bus horrible uncomfortable experience",
    "excellent punctual clean comfortable bus friendly driver great",
    "driver was aggressive rude shouting very bad experience",
    "pleasant journey on time arrival comfortable clean bus",
    "horrible experience late arrival dirty bus rude driver",
    "good service clean bus comfortable seats driver helpful",
    "driver was very rude aggressive dangerous unsafe horrible",
    "excellent journey comfortable seats on time arrival satisfied",
    "terrible overcrowded dirty bus rude driver horrible experience",
    "clean comfortable bus friendly driver professional excellent",
    "driver was dangerous speeding reckless unsafe scary",
    "good comfortable journey driver was helpful on time",
    "excellent service punctual clean comfortable bus friendly driver",
    "very bad experience rude aggressive driver terrible horrible",
    "pleasant comfortable journey on time arrival friendly driver",
    "horrible dirty overcrowded bus terrible uncomfortable horrible",
    "great driver very friendly helpful comfortable clean bus",
    "bad experience driver was not cooperative rude unhelpful",
    "satisfied with the journey overall decent experience today",
    "not happy with the service driver was unprofessional",
    "very good trip comfortable ride helpful driver on time",
    "disappointed with the journey late and uncomfortable bus",
    "the ride was okay nothing exceptional average experience",
    "driver seemed tired but managed to drive safely okay",
    "bus could be cleaner but journey was acceptable overall",
    "good enough for the price paid comfortable journey",
    "had a decent experience driver was moderately helpful",
    "journey was fine arrived a bit late but acceptable",
    "the bus service was mediocre could be much better",
    "not impressed with the service but it was okay",
    "ride was bumpy but driver was friendly and polite",
    "average bus service nothing to complain about really",
    "driver was okay not very friendly but professional",
    "bus was a bit late but comfortable enough journey",
    "decent ride overall driver could improve attitude slightly",
    "satisfactory service arrived on time comfortable enough seats",
    "bus was acceptable clean enough driver was neutral",
    "journey was fine overall no major complaints today",
    "average experience driver was neither rude nor friendly",
    "okay service bus was clean enough arrived on time",
]

print(f"Training corpus: {len(training_texts)} documents")

tfidf = TfidfVectorizer(
    max_features=3000,
    ngram_range=(1, 2),
    min_df=1,
    sublinear_tf=True,
)
tfidf.fit(training_texts)

actual = len(tfidf.vocabulary_)
print(f"Vocabulary size: {actual} features")
print(f"Model expects: 3000 TF-IDF + 35 meta = 3035 total")

out_path = os.path.join(MODELS_DIR, "vectorizer_v5.pkl")
joblib.dump(tfidf, out_path)
print(f"Saved to: {out_path}")
print("Done! Restart the ML service now.")